"""add category_id fabric product_type to product

Revision ID: 035b0009a53c
Revises: 1abff597a149
Create Date: 2026-06-20 14:41:03.642596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '035b0009a53c'
down_revision: Union[str, None] = '1abff597a149'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('category_id', sa.String(), nullable=True))
    op.add_column('products', sa.Column('fabric', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('product_type', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_index(op.f('ix_products_product_type'), 'products', ['product_type'], unique=False)
    op.create_foreign_key(None, 'products', 'categories', ['category_id'], ['id'])
    op.create_unique_constraint(None, 'review_helpfuls', ['review_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'review_helpfuls', type_='unique')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_index(op.f('ix_products_product_type'), table_name='products')
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.drop_column('products', 'product_type')
    op.drop_column('products', 'fabric')
    op.drop_column('products', 'category_id')
    # ### end Alembic commands ###
